name: Sync Upstream
 
on:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
 
      - name: Syncing with upstream
        uses: cpina/github-actions-sync-fork@master
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          UPSTREAM_REMOTE_URL: 'https://github.com/original-owner-username/original-repository.git'
