name: Sync Upstream
 
on:
  schedule:
    - cron: '*/30 * * * *'
 
jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: 'main'
 
      - name: Sync Upstream
        uses: cviebrock/github-actions-setup-gitea@master
        with:
          version: '2.20.1'
 
      - name: Fetch Upstream
        run: |
          git fetch upstream
      - name: Rebase Upstream
        run: |
          git rebase upstream/main
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
